---
apiVersion: v1
appVersion: "1.1.0"
description: "Container Storage Interface (CSI) driver,
provisioner, snapshotter, and attacher for Ceph RBD"
name: ceph-csi-rbd
version: 1.1.0
keywords:
  - ceph
  - rbd
  - ceph-csi
home: https://github.com/ceph/ceph-csi
sources:
  - https://github.com/ceph/ceph-csi/tree/csi-v1.0/deploy/rbd/helm
