---
rbac:
  create: true

serviceAccounts:
  attacher:
    create: true
    name:
  nodeplugin:
    create: true
    name:
  provisioner:
    create: true
    name:

socketDir: /var/lib/kubelet/plugins/rbd.csi.ceph.com
socketFile: csi.sock
registrationDir: /var/lib/kubelet/plugins_registry
volumeDevicesDir: /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices
driverName: rbd.csi.ceph.com
configMapName: ceph-csi-config

attacher:
  name: attacher
  enabled: true
  replicaCount: 1

  image:
    repository: quay.io/k8scsi/csi-attacher
    tag: v1.1.1
    pullPolicy: IfNotPresent

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

nodeplugin:
  name: nodeplugin

  registrar:
    image:
      repository: quay.io/k8scsi/csi-node-driver-registrar
      tag: v1.1.0
      pullPolicy: IfNotPresent

    resources: {}

  plugin:
    image:
      repository: quay.io/cephcsi/cephcsi
      # for stable functionality replace canary with latest release version
      tag: canary
      pullPolicy: IfNotPresent

    resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

provisioner:
  name: provisioner

  replicaCount: 1

  image:
    repository: quay.io/k8scsi/csi-provisioner
    tag: v1.2.0
    pullPolicy: IfNotPresent

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

snapshotter:
  image:
    repository: quay.io/k8scsi/csi-snapshotter
    tag: v1.1.0
    pullPolicy: IfNotPresent

  resources: {}

resizer:
  image:
    repository: quay.io/k8scsi/csi-resizer
    tag: canary
    pullPolicy: IfNotPresent

  resources: {}
