---
apiVersion: v1
appVersion: v2.1-canary
description: "Container Storage Interface (CSI) driver,
provisioner, and attacher for Ceph cephfs"
name: ceph-csi-cephfs
version: 2.1-canary
keywords:
  - ceph
  - cephfs
  - ceph-csi
home: https://github.com/ceph/ceph-csi
sources:
  - https://github.com/ceph/ceph-csi/tree/master/charts/ceph-csi-cephfs
icon: https://raw.githubusercontent.com/ceph/ceph-csi/master/assets/ceph-logo.png
