---
apiVersion: v1
appVersion: v3.3.1
description: "Container Storage Interface (CSI) driver,
provisioner, snapshotter and attacher for Ceph cephfs"
name: ceph-csi-cephfs
version: 3.3.1-canary
keywords:
  - ceph
  - cephfs
  - ceph-csi
home: https://github.com/ceph/ceph-csi
sources:
  - https://github.com/ceph/ceph-csi/tree/devel/charts/ceph-csi-cephfs
icon: https://raw.githubusercontent.com/ceph/ceph-csi/devel/assets/ceph-logo.png
