kind: Service
apiVersion: v1
metadata:
  name: csi-rbdplugin-attacher
  labels:
    app: csi-rbdplugin-attacher
spec:
  selector:
    app: csi-rbdplugin-attacher
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: csi-rbdplugin-attacher
spec:
  serviceName: "csi-rbdplugin-attacher"
  replicas: 1
  template:
    metadata:
      labels:
        app: csi-rbdplugin-attacher
    spec:
      serviceAccount: csi-attacher
      containers:
        - name: csi-rbdplugin-attacher
          image: quay.io/k8scsi/csi-attacher:v1.0.1
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/kubelet/plugins_registry/csi-rbdplugin/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/kubelet/plugins_registry/csi-rbdplugin
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/csi-rbdplugin
            type: DirectoryOrCreate
