[[constraint]]
  name = "github.com/container-storage-interface/spec"
  version = "~1.1.0"

[[override]]
  revision = "5db89f0ca68677abc5eefce8f2a0a772c98ba52d"
  name = "github.com/docker/distribution"

#fixes https://github.com/golang/dep/issues/1799
[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.10.0"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-middleware"
  version = "1.0.0"

[[override]]
  version = "kubernetes-1.17.0"
  name = "k8s.io/apimachinery"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "=v1.17.0"

[[override]]
  version = "kubernetes-1.17.0"
  name = "k8s.io/api"

[[override]]
  version = "kubernetes-1.17.0"
  name = "k8s.io/apiserver"

[[override]]
  version = "kubernetes-1.17.0"
  name = "k8s.io/cli-runtime"

[[override]]
  name = "github.com/golang/protobuf"
  version = "1.1.0"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.17.0"

[[override]]
  name = "github.com/kubernetes-csi/external-snapshotter"
  version = "v1.1.0"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.17.0"

[[override]]
  name = "k8s.io/kube-aggregator"
  version = "kubernetes-1.17.0"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-prometheus"
  version = "1.2.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "1.1.0"

[[constraint]]
  name = "github.com/kubernetes-csi/csi-lib-utils"
  version = "v0.6.1"

[prune]
  go-tests = true
  non-go = true
  unused-packages = true

# Prevent dep from pruning
[[prune.project]]
  name = "github.com/kubernetes-csi/external-snapshotter"
  non-go = false

[[constraint]]
  branch = "master"
  name = "k8s.io/utils"
