---
kind: Template
apiVersion: v1
metadata:
  name: jjb-validate
objects:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      labels:
        app: jjb-validate
        jjb/session: "${SESSION}"
      name: jjb-validate
    spec:
      ttlSecondsAfterFinished: 0
      backoffLimit: 1
      template:
        metadata:
          labels:
            app: jjb-validate
            jjb/session: "${SESSION}"
        spec:
          containers:
            - name: jjb-validate
              image: image-registry.openshift-image-registry.svc:5000/ceph-csi/jjb:latest
              env:
                - name: GIT_REPO
                  value: "${GIT_REPO}"
                - name: GIT_REF
                  value: "${GIT_REF}"
          restartPolicy: Never
parameters:
  - name: SESSION
    description: unique ID for the session to track the pod for the job
    required: true
  - name: GIT_REF
    description: the git branch or other ref to checkout and validate
    value: ci/centos
    required: false
  - name: GIT_REPO
    description: the git repo or other fork to checkout and validate
    value: https://github.com/ceph/ceph-csi
    required: false
