kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: {{ include "ceph-csi-rbd.attacher.fullname" . }}
  labels:
    app: {{ include "ceph-csi-rbd.name" . }}
    chart: {{ include "ceph-csi-rbd.chart" . }}
    component: {{ .Values.attacher.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: {{ include "ceph-csi-rbd.attacher.fullname" . }}
  replicas: {{ .Values.attacher.replicas }}
  selector:
    matchLabels:
      app: {{ include "ceph-csi-rbd.name" . }}
      component: {{ .Values.attacher.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "ceph-csi-rbd.name" . }}
        chart: {{ include "ceph-csi-rbd.chart" . }}
        component: {{ .Values.attacher.name }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      serviceAccountName: {{ include "ceph-csi-rbd.serviceAccountName.attacher" . }}
      containers:
        - name: csi-rbdplugin-attacher
          image: "{{ .Values.attacher.image.repository }}:{{ .Values.attacher.image.tag }}"
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: "{{ .Values.socketDir }}/{{ .Values.socketFile }}"
          imagePullPolicy: {{ .Values.attacher.image.pullPolicy }}
          volumeMounts:
            - name: socket-dir
              mountPath: {{ .Values.socketDir }}
          resources:
{{ toYaml .Values.attacher.resources | indent 12 }}
      volumes:
        - name: socket-dir
          hostPath:
            path: {{ .Values.socketDir }}
            type: DirectoryOrCreate
    {{- if .Values.attacher.affinity -}}
      affinity:
{{ toYaml .Values.attacher.affinity . | indent 8 }}
    {{- end -}}
    {{- if .Values.attacher.nodeSelector -}}
      nodeSelector:
{{ toYaml .Values.attacher.nodeSelector | indent 8 }}
    {{- end -}}
    {{- if .Values.attacher.tolerations -}}
      tolerations:
{{ toYaml .Values.attacher.tolerations | indent 8 }}
    {{- end -}}
