apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ .Values.driverName }}
  labels:
    app: {{ include "ceph-csi-cephfs.name" . }}
    chart: {{ include "ceph-csi-cephfs.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- with .Values.commonLabels }}{{ toYaml . | trim | nindent 4 }}{{- end }}
spec:
  attachRequired: false
  podInfoOnMount: false
  fsGroupPolicy: {{ .Values.CSIDriver.fsGroupPolicy }}
  seLinuxMount: true
