{{ if semverCompare ">=1.18" .Capabilities.KubeVersion.GitVersion }}
apiVersion: storage.k8s.io/v1
{{ else }}
apiVersion: storage.k8s.io/v1betav1
{{ end }}
kind: CSIDriver
metadata:
  name: {{ .Values.driverName }}
spec:
  attachRequired: true
  podInfoOnMount: false
